# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users)
  return users;
}
getUser(-1)
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
The function is unsafe because there is no error handling. It is not wrapped in a try/catch block, so any errors that occur during the fetch operation or JSON parsing will cause the app to crash. For example, passing -1 as an argument will result in a request to an invalid URL. If the server responds with an error, the function will throw an unhandled error, potentially crashing the application.

# Teacher Feedback